services:
    app:
        build:
            args:
                user: user
                uid: 1000
            context: ..
            dockerfile: .docker/Dockerfile
        image: ${APP_NAME}
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ../:/var/www
        networks:
            - laravel-project-network

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - laravel-project-network

    node:
        build:
            context: ..
            dockerfile: .docker/node.dockerfile
        working_dir: /var/www/
        volumes:
            - ../:/var/www
            - ${HOME}/.npm:${HOME}/.npm
        command: bash -c "npm install && npm run build"
        networks:
            - laravel-project-network

networks:
    laravel-project-network:
        driver: bridge
